version: '3.6'
services:

  ## Enterprise frontend service #########################################
  enterprise-frontend-app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "23123:3000"
